### ISSUE TITLE
Class 'QueryParser\\ParserRequestFactory' not found

### ISSUE THREAD

**Issue by kikoseijo** [rlacerda83/lumen-api-query-parser#14]
Class 'QueryParser\\ParserRequestFactory' not found
Any suggestions?

thanks-.

**Comment by rlacerda83** [comment]
Please, provide more info!
PHP version? Do you have a trace error?

**Comment by kikoseijo** [comment]
Got it working doing a 

```php
composer require rlacerda83/query-parser:master
```

Got a question, package seems to work fine, I'm using fork and added 'limit' as another var that will remove from query, same as 'page', doing this because I give developers paginate options with this value.

You think you can include in yours?

Im also doing a trick to pull eloquent instead of query builded, just to get extended functionality from Eloquent, like automatic soft delete filtering, etc..

```php
// To run Eloquent use this
$queryParser  = ParserRequestFactory::createParser($request, Model::class, Model::class);
 // To run QueryBuilder use this
$queryParser  = ParserRequestFactory::createParser($request,Model::class);
```

At development stage, I think this is what this package its for, DB efficiency its not an issue for me. This is maybe, something could be done in a diferent manner.

Anyway, love it, really clever package this one. Gratz.
